---
deployment:
  tasks:
    - export DEPLOYPATH=/home/priseghy/public_html
    - /bin/cp -rf index.html $DEPLOYPATH/
    - /bin/cp -rf admin.html $DEPLOYPATH/
    - /bin/cp -rf api.php $DEPLOYPATH/
    - /bin/cp -rf data.json $DEPLOYPATH/
    - /bin/cp -rf favicon.svg $DEPLOYPATH/
    - /bin/cp -rf images $DEPLOYPATH/
    - /bin/cp -rf api $DEPLOYPATH/
    - /bin/cp -rf uploads $DEPLOYPATH/
